package cz.hsrs.db.model;

import java.sql.ResultSet;
import java.sql.SQLException;
// default package
// Generated 3.6.2008 8:21:13 by Hibernate Tools 3.2.2.GA

import cz.hsrs.db.DBObject;

/**
 * Phenomenon generated by hbm2java
 */
public class Phenomenon implements DBObject{

	@Override
	public DBObject getDBObject(ResultSet set) throws SQLException {
		// TODO Auto-generated method stub
		return new Phenomenon(set);
	}

	private String phenomenonId;
	private String phenomenonName;
	private String unit;


	public Phenomenon(ResultSet set) throws SQLException{
		
		this.phenomenonId = set.getString("phenomenon_id");
		this.phenomenonName = set.getString("phenomenon_name");
		this.unit = set.getString("unit");	
		}

	public Phenomenon(String phenomenonId, String unit, String valuetype) {
		this.phenomenonId = phenomenonId;
		this.unit = unit;
		
	}

	public Phenomenon(String phenomenonId, String phenomenonName, String unit,
			String valuetype) {
		this.phenomenonId = phenomenonId;
		this.phenomenonName = phenomenonName;
		this.unit = unit;
	
	}

	public String internalGetPhenomenonId() {
		return this.phenomenonId;
	}


	public String getPhenomenonName() {
		return this.phenomenonName;
	}


	public String getUnit() {
		return this.unit;
	}


}
